### ISSUE TITLE
Automatically append caption HTML to featured image HTML?

### ISSUE THREAD

**Issue by cconover** [cconover/wp-featured-image-caption#14]
Look into the option for the plugin to modify the function that renders the featured image in a theme to append the featured image caption HTML to the featured image HTML. This would remove the need to modify theme code, and make installation and usage simpler for non-technical users.

**Comment by avluis** [comment]
I know that if I need to add any features to my theme, I would need to use child themes and modify the functions.php file.
From there I can filter output and do whatever I needed.

But after installing a plugin that lets me add actions and filters to my WP install, then I don't even need a child theme.
I just add my function there.

I learned all this when I was investigation hAtom feeds, here are those functions I needed to add:
```php
//mod content
function hatom_mod_post_content ($content) {
  if ( in_the_loop() && !is_page() ) {
    $content = '<span class="entry-content">'.$content.'</span>';
  }
  return $content;
}
add_filter( 'the_content', 'hatom_mod_post_content');

//add hatom data
function add_mod_hatom_data($content) {
    $t = get_the_modified_time('F jS, Y');
    $author = get_the_author();
    $title = get_the_title();
    if ( is_single() || is_page()) {
        $content .= '<div class="hatom-extra" style="display:none;visibility:hidden;"><span class="entry-title">'.$title.'</span> was last modified: <span class="updated">'.$t.'</span> by <span class="author vcard"><span class="fn">'.$author.'</span></span></div>';
    }
    return $content;
    }
add_filter('the_content', 'add_mod_hatom_data');
```
I hope this helps somewhat.

**Comment by cconover** [comment]
Yeah, that was my thought. I need to look into all possible functions that can be used to render the featured image in a theme, and filter them to append the HTML for the caption.

**Comment by avluis** [comment]
Just tried out your update, pretty nice to see it working.
I do have one more request (this may need its own issue opened).
Take a look at how my theme display the featured image on my (website)[https://avnet.ws].
This applies to any other pages with a featured image.
See where I have the featured image caption - I use a plugin to create a shortcode with the following:
```php
echo "<p><i>Featured Image Credit: </i></p>"; cc_featured_image_caption();
```
I then insert the shortcode [featuredImageCaption] at the end of my posts and get the results you see.

Any way to have this functionality built-in since the groundwork is in place (from what I have seen of the current build) to have a shortcode for those that want to have the featured image caption separate from the image?

**Comment by cconover** [comment]
It's funny you mention that, I was literally just thinking about 20 minutes ago of adding a shortcode.

Yeah, go ahead and open a new issue on it so it can be tracked separately.

**Comment by avluis** [comment]
Awesome! I will go ahead and open the issue with as much detail as I can.
