### ISSUE TITLE
Request: Enhance featured image caption insert shortcode

### ISSUE THREAD

**Issue by avluis** [cconover/wp-featured-image-caption#17]
As mentioned in a prior issue - https://github.com/cconover/wp-featured-image-caption/issues/14#issuecomment-89337162, for those that would like to separate the featured image caption from the featured image and insert where they wish, via shortcode.

An example can be seen on my own [website](https://avnet.ws) - the theme displays the featured image on top of the content and above the title, while the featured image caption is displayed at the bottom of the content along with a title.
This is done by inserting the following with a different plugin at the moment, but because of how much I use it (sorry, don't have usage metrics), it should be part of this plugin:

```php
echo "<p><i>Featured Image Credit: </i></p>"; cc_featured_image_caption();
```

If the user has "Automatically add the caption to the featured image" option disabled, then this feature should be in effect.
They would then get the following options:

Include custom title (in the above example, "Featured Image Credit: " is the title).
If a title is included, simple formatting options like bold, italics, underline, etc. (in the example above, the title is in italics) and simple tags to surround said title (example above, paragraph tags keep it separated from the featured image caption).

As for the shortcode, I think the same shortcode can still be used.
If the user has any of the options above enabled, then they essentially format the way the shortcode is displayed, if not, then the shortcode displays as it always has.

**Comment by cconover** [comment]
I think adding a shortcode is a great idea.

Version 0.5.0, in addition to adding support for #14 also modified the theme function as follows:

- If "automatic caption adding" is enabled in plugin options, the theme function does not output anything. This is to prevent accidental duplicate content.
- You can no longer toggle attribution data to be included. You either get everything the caption data has, or nothing.
- You can choose whether to get back full HTML, or the raw array of caption data

For most people this is fine, but for people who want to use the caption data in places on their site where a theme function isn't feasible, or outside of the already considered methods, a shortcode is a great answer.

Here is my concept for the functionality of the shortcode.

Base syntax: `[cc-featured-image-caption]`

**Parameters**
- `caption-text` boolean, whether to output caption text. Default `true`.
- `source-text` boolean, whether to output image source attribution text. Default `true`. If `false`, the value of `source-url` will be ignored and be considered `false`, so no source information will be included.
- `source-url` boolean, whether to make the source attribution a link using the source URL. Default `true`. If this is true, the value of `source-text` is ignored and source text will be included automatically. If this is true and 1) no URL is set, and 2) `source-text` is not specified `false`, just source text will be shown.

Full caption, all available data:

    [cc-featured-image-caption]

Just caption text:

    [cc-featured-image-caption source-text=false]

Just source text:

    [cc-featured-image-caption caption-text=false source-url=false]

Just source as a link:

    [cc-featured-image-caption caption-text=false]

The shortcode will always output the fully assembled HTML, accounting for parameters.

**Comment by avluis** [comment]
Awesome implementation, love how easy it is to include the additional parameters.
I don't think I have anything to add, very well thought out.

**Comment by cconover** [comment]
Actually, I'm going to revise my initial spec. The shortcode name will remain the same, but I want to simplify the parameter syntax.

If just the shortcode is provided without parameters:

    [cc-featured-image-caption]

Then all parameters will be assumed `true`, and the HTML output will reflect this.

However, if any parameters are listed, only those parameters will be accounted for in the HTML.

**Examples**
Just the caption text:

    [cc-featured-image-caption caption-text]

Just the source text:

    [cc-featured-image-caption source-text]

Just the source information as a link:

    [cc-featured-image-caption source-url]

*As before, if `source-url` is `true` then `source-text` is assumed `true` since the text is required as part of the link.*

Just the caption text and source text with no link:

    [cc-featured-image-caption caption-text source-text]

**HTML Output**
HTML that is output by the shortcode will have the same markup as HTML that is automatically added to the featured image, or is output by the theme function. The same classes will be available for CSS styling, etc.

**Comment by cconover** [comment]
I am going to add one additional parameter: `plaintext`

This is also boolean, and if specified the shortcode will return just the text of the elements requested, no HTML.

If `plaintext` is the only attribute specified in the shortcode, the result will be the caption text and the source text as a single string. The source URL will be omitted, unless explicitly requested.

If `source-url` and `plaintext` are both specified, then the shortcode will output just the URL, without any HTML. You cannot combine `source-url` with any of the other parameters when requesting plaintext, since this could result in some messy output. If `source-url` is specified in conjunction with `plaintext`, only the source URL as plaintext will be returned, and any other parameters will be ignored. If for some reason you need all three pieces together (caption text, source text and source URL) all as plaintext, you can use two separate shortcode calls in a row.

**Examples**
The caption text and source text as a single plaintext string:

    [cc-featured-image-caption plaintext]

Just the caption text as a plaintext string:

    [cc-featured-image-caption caption-text plaintext]

Just the source text as a plaintext string:

    [cc-featured-image-caption source-text plaintext]

Just the source URL as a plaintext string:

    [cc-featured-image-caption source-url plaintext]

**Comment by cconover** [comment]
I've put up [v0.6.0-beta1](https://github.com/cconover/wp-featured-image-caption/releases/tag/v0.6.0-beta1) which adds the shortcode. Please test it and provide feedback.

As a result of developing the shortcode, I've made a few changes to the syntax.

**Shortcode Name**
The name remains the same as it has always been described:

    [cc-featured-image-caption]

**Formats**
The shortcode supports two output formats: HTML and plaintext. It defaults to HTML. To explicitly choose a format, pass the `format` attribute in the shortcode with either `html` or `plaintext` as the value.

To get back HTML, either omit `format` from the shortcode or do the following:

    [cc-featured-image-caption format="html"]

To get back plain text, do the following:

    [cc-featured-image-caption format="plaintext"]

**Flags**
By default, the shortcode will return all of the caption data available to the chosen output format. To explicitly choose what caption data should be included in the result, you can add flags to the shortcode.

The available tags for each format are as follows.

**HTML**: `caption-text`, `source-text`, `source-link`  
**Plain text**: `caption-text`, `source-text`

Note that `source-link` is only available for HTML. You cannot get back the source URL as plain text. The URL is only used in creating an HTML link to the source.

If you add the `source-link` flag, `source-text` is assumed since you need the source text to create the link.

**Examples**
Here are some examples of the shortcode with flags and formats.

Full HTML, all caption information.

    [cc-featured-image-caption]

HTML, just caption text.

    [cc-featured-image-caption caption-text]

HTML, just source text.

    [cc-featured-image-caption source-text]

HTML, just source link.

    [cc-featured-image-caption source-link]

Plain text, all available caption data.

    [cc-featured-image-caption format="plaintext"]

Plain text, just caption text.

    [cc-featured-image-caption caption-text]

Plain text, just source text.

    [cc-featured-image-caption source-text]

**Comment by cconover** [comment]
As soon as I posted my last message I realized how to support requesting the source URL in plain text. I've released [v0.6.0-beta2](https://github.com/cconover/wp-featured-image-caption/releases/tag/v0.6.0-beta2) which adds support for that.

This release adds the following flag to the plain text format: `source-url`

The full syntax for this is:

    [cc-featured-image-caption source-url format="plaintext"]

This flag is only valid when requesting the plain text format, and will have no effect for HTML. If `source-url` is passed for plain text, you will ONLY get back the source URL and no other caption elements, regardless of what other flags are included. For example, if you type:

    [cc-featured-image-caption caption-text source-url format="plaintext"]

You will only get back the URL and `caption-text` will be ignored.

**Comment by avluis** [comment]
Got it, I'll give the latest beta a try and report back.

**Comment by cconover** [comment]
So far my testing has not surfaced any bugs.

**Comment by cconover** [comment]
I have created a page on the repo wiki to [document the shortcode](https://github.com/cconover/wp-featured-image-caption/wiki/Shortcode).

**Comment by cconover** [comment]
I have released [v0.6.0-beta3](https://github.com/cconover/wp-featured-image-caption/releases/tag/v0.6.0-beta3) which adds better handling of format-specific flags.

**Comment by cconover** [comment]
[v0.6.0-beta4](https://github.com/cconover/wp-featured-image-caption/releases/tag/v0.6.0-beta4) fixes a bug introduced in beta3 involving the format-specific flag check.

**Comment by avluis** [comment]
I did not encounter any issues while using v0.6.0-beta2. I'll give the new one a try.

**Comment by cconover** [comment]
Ok cool. So far my tests of beta4 are not showing any issues. Unless you discover any, I'm going to release v0.6.0 tonight or tomorrow.
